---
- name: Apply Galaxy Role
  hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.galaxycloud
      GALAXY_ADMIN_EMAIL: "admin@elixir-italy.org"
      GALAXY_ADMIN_USERNAME: "admin" 
      GALAXY_VERSION: "release_17.05"
      galaxy_instance_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDy787GZIVdHW7QV+Wu2q9q5k5CiTOq04ENioVig88IIVGNqi8qiX+3fhZx/w2hhlz6AePrYu8CfVPplCRdSMjP46av53V1M7r0+yqJvuk1PC2f/rSoEL95TvaeiV28+5Wy4MC58UvYuewuhIHcbfPiXHf3NEE3scd38GXCYKLhAP28mUQ950Ar4SoWv4irv21maJwkwqn5AYXcy1yrbBZtaTbQELVPa/E6X9j+k29bn32ITmmtKBA3ne/QlFRaaYI3XggvMXhhSSIYsJUdlSOjUTriB2DraHsxMGfOPjmPXkjvrXp9MfOzjMg10fb7K2Mda8u/ujK/dvx3BnhlSIpn marco@marco-Latitude-3440"
      set_pgsql_random_password: false
      set_proftpd_random_password: false
      galaxy_db_dir: '/home/galaxy/galaxy/database'
      tool_deps_path: '/home/galaxy/tool_deps'
      conda_prefix: '/home/galaxy/tool_deps/_conda'
      job_work_dir: 'database/jobs_directory'

#- name: Install tools
#  hosts: localhost
#  connection: local
#  roles:
#    - role: indigo-dc.galaxycloud-tools
#      galaxy_flavor: 'galaxy-rna-workbench'
#      when: galaxy_flavor != 'galaxy-no-tools'
#
#    - role: indigo-dc.galaxycloud-tooldeps

- name: Post installation tasks
  hosts: localhost
  connection: local
  pre_tasks:
    - set_fact:
        galaxy_user: 'galaxy'
        galaxy_instance_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDy787GZIVdHW7QV+Wu2q9q5k5CiTOq04ENioVig88IIVGNqi8qiX+3fhZx/w2hhlz6AePrYu8CfVPplCRdSMjP46av53V1M7r0+yqJvuk1PC2f/rSoEL95TvaeiV28+5Wy4MC58UvYuewuhIHcbfPiXHf3NEE3scd38GXCYKLhAP28mUQ950Ar4SoWv4irv21maJwkwqn5AYXcy1yrbBZtaTbQELVPa/E6X9j+k29bn32ITmmtKBA3ne/QlFRaaYI3XggvMXhhSSIYsJUdlSOjUTriB2DraHsxMGfOPjmPXkjvrXp9MfOzjMg10fb7K2Mda8u/ujK/dvx3BnhlSIpn marco@marco-Latitude-3440"
        GALAXY_ADMIN_EMAIL: "admin@elixir-italy.org"

  tasks:
    - name: Delete Galaxy administrator
      command: "/home/galaxy/galaxy/.venv/bin/python /usr/local/bin/delete_galaxy_user.py --user {{ GALAXY_ADMIN_EMAIL }}"
      args:
        chdir: '/home/galaxy/galaxy/'
      environment:
        PYTHONPATH: '/home/galaxy/galaxy/lib'
        VIRTUAL_ENV: '/home/galaxy/galaxy.venv'

    - name: Remove admin_users from galaxy.ini
      replace:
        dest: /home/galaxy/galaxy/config/galaxy.ini
        regexp: 'admin_users = {{GALAXY_ADMIN_EMAIL}}'
        replace: '#admin_users = None'

    - name: 'Inject ssh public key - {{ galaxy_user }}'
      authorized_key:
        user: '{{ galaxy_user }}'
        key: '{{ galaxy_instance_key_pub }}'
        state: absent
#    - name: 'Inject ssh public key - root'
#      authorized_key:
#        user: 'root'
#        key: '{{ galaxy_instance_key_pub }}'
#        state: absent
#    - name: 'Remove centos user'
#      user:
#        name: 'centos'
#        state: absent
#        remove: yes
