heat_template_version: 2014-10-16

description: setup server

resources:
  vm_os:
    type: galaxyinstance.yaml
    properties:
      key_name: mtangaro-key
      vm_name: galaxy_server
      image_id: 7b504908-baf7-48d3-b7f1-aac52ad40768 # CentOS 7.4 Galaxy
      instance_type: small #4cpu-4GB-20dsk
      availability_zone: nova
      net_id: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333 #pub-ip
