heat_template_version: 2014-10-16

description: setup Galaxy + NGINX + Postgresql + uWSGI + PROFTPd

resources:
  vm_os:
    type: galaxyinstance.yaml
    properties:
      key_name: mtangaro-key
      vm_name: centos-development-image
      image_id: bd2ebc86-7930-4f90-af7b-ff94b982a2eb # Generic CentOS 7 cloud image, 2016-06-07
      instance_type: small #4cpu-4GB-20dsk
      availability_zone: nova
      volume_size: 1
      mountpoint: /export
      ref_volume_size: 1
      ref_mountpoint: /refdata
      net_id: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333 #pub-ip
      admin_username: "mtangaro"
      admin_mailaddr: "ma.tangaro@gmail.com"
      flavor: "galaxy-REVIEW"
      ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDy787GZIVdHW7QV+Wu2q9q5k5CiTOq04ENioVig88IIVGNqi8qiX+3fhZx/w2hhlz6AePrYu8CfVPplCRdSMjP46av53V1M7r0+yqJvuk1PC2f/rSoEL95TvaeiV28+5Wy4MC58UvYuewuhIHcbfPiXHf3NEE3scd38GXCYKLhAP28mUQ950Ar4SoWv4irv21maJwkwqn5AYXcy1yrbBZtaTbQELVPa/E6X9j+k29bn32ITmmtKBA3ne/QlFRaaYI3XggvMXhhSSIYsJUdlSOjUTriB2DraHsxMGfOPjmPXkjvrXp9MfOzjMg10fb7K2Mda8u/ujK/dvx3BnhlSIpn marco@marco-Latitude-3440"
