heat_template_version: 2014-10-16

description: setup Galaxy + NGINX + Postgresql + uWSGI + PROFTPd

resources:
  vm_os:
    type: galaxyinstance.yaml
    properties:
      key_name: mtangaro-key
      vm_name: galaxy-test
      image_id: 5e648fd9-ddb7-452a-b5f6-09f4e1ac0b97 # CentOS-7-x86_64-HEAT-1704
      instance_type: small #4cpu-4GB-20dsk
      availability_zone: nova
      net_id: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333 #pub-ip
      release: "release_17.01" # "master" # Galaxy release version
      flavor: "galaxy-TESTING"
