heat_template_version: 2014-10-16

description: setup Galaxy + NGINX + Postgresql + uWSGI + PROFTPd

resources:
  vm_os:
    type: galaxyinstance.yaml
    properties:
      key_name: mtangaro-key
      vm_name: galaxy-mt
      #image_id: 5e648fd9-ddb7-452a-b5f6-09f4e1ac0b97 # CentOS-7-x86_64-HEAT-1704
      image_id: 9d2996b7-3242-4b71-8c4c-1cb4c93eb7f7 # CentOS-7-x86_64-HEAT-1704 galaxy-mesos
      instance_type: small #4cpu-4GB-20dsk
      availability_zone: nova
      #net_id: fe82ef7b-4bb7-4c1e-b4ec-ec5c1b0c7333 #pub-ip
      net_id: d21a98a8-30ab-486a-a4d0-a11b3080b304 #priv-ip galaxy-mesos
      release: "release_17.01" # "master" # Galaxy release version
      flavor: "galaxy-TESTING"
